#!/usr/bin/env python3

import re
import sys

from os.path import expanduser, basename
from glob import glob
from datetime import datetime

histfiles = glob(expanduser('~/.bash_history/local/history_*'))
histfiles = sorted(histfiles, key=lambda x: datetime.strptime(basename(x).rsplit('_',1)[-1], '%Y-%m'))
histfiles = histfiles[-5:]

patterns = sys.argv[1:]

for filename in histfiles:
    last_timestamp = None
    cmds = {}

    with open(filename, 'r') as f:
        while True:

            line = f.readline()
            if len(line) == 0:
                break

            line = line.rstrip('\n')
            if len(line) == 0:
                continue

            if line[0] == '#':
                try:
                    last_timestamp = datetime.fromtimestamp(int(line[1:]))
                except:
                    pass
                continue

            def does_match():
                for pattern in patterns:
                    if re.search(pattern, line, re.IGNORECASE) is None:
                        return False

                return True

            if not does_match():
                continue

            if line not in cmds:
                cmds[line] = []

            cmds[line].append(last_timestamp)

    print('%s   (%dx)' % ( filename, sum([ len(_) for _ in cmds.values() ] )))

    for line, timestamps in sorted(cmds.items(), key=lambda _: sorted(_[1], reverse=True)[0]):
        last_timestamp = sorted(timestamps, reverse=True)[0]
        print('%s  |  %3dx | %s' % ( str(last_timestamp), len(timestamps), line ))
